packages:
  - 'packages/*'
allowBuilds:
  '@reown/appkit': false
  bufferutil: false
  esbuild: false
  msw: false
  sharp: false
  utf-8-validate: false
  workerd: true
ignoredOptionalDependencies:
  - "@base-org/account"
  - "@safe-global/safe-apps-provider"
  - "@safe-global/safe-apps-sdk"
  - "@lit/react"
